authors:
  -
    name: "Carlos Camacho"
    contact_email: "carloscamachoucv@gmail.com"
    bio:
        Author bio [link](https://www.carlosdcg.com)

faq:
  -
    question: "What is included in this book"
    answer: "A practical roadmap for Chef"




repo_url: 'https://github.com/carlosdcg/chefbyexample_book'
contact_email: 'carloscamachoucv@gmail.com'
hide_custom_domain_footer: false

